swagger: '2.0'
basePath: /api/v3/oneprovider
info:
  $ref: ./info/index.yaml
paths:
  $ref: ./paths/index.yaml
definitions:
  $ref: ./definitions/index.yaml
tags:
  - name: Data
    description: Space and file related operations
  - name: Replication
    description: Replication, file distribution and transfer control operations
  - name: Monitoring
    description: Metrics and change events monitoring related operations
securityDefinitions:
  api_key:
    type: apiKey
    name: X-Auth-Key
    in: header
  basic:
    type: basic